// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.27.0--rc1
// source: game/backpack.proto

package game

import (
	_ "github.com/ravinggo/game/common/basepb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BackpackErrorCode int32

const (
	BackpackErrorCode_BackpackErrorItemNotEnough BackpackErrorCode = 0
)

// Enum value maps for BackpackErrorCode.
var (
	BackpackErrorCode_name = map[int32]string{
		0: "BackpackErrorItemNotEnough",
	}
	BackpackErrorCode_value = map[string]int32{
		"BackpackErrorItemNotEnough": 0,
	}
)

func (x BackpackErrorCode) Enum() *BackpackErrorCode {
	p := new(BackpackErrorCode)
	*p = x
	return p
}

func (x BackpackErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BackpackErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_game_backpack_proto_enumTypes[0].Descriptor()
}

func (BackpackErrorCode) Type() protoreflect.EnumType {
	return &file_game_backpack_proto_enumTypes[0]
}

func (x BackpackErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BackpackErrorCode.Descriptor instead.
func (BackpackErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_game_backpack_proto_rawDescGZIP(), []int{0}
}

type Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Cid   int64 `protobuf:"varint,2,opt,name=cid,proto3" json:"cid,omitempty"`
	Value int64 `protobuf:"varint,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Item) Reset() {
	*x = Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_backpack_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_game_backpack_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_game_backpack_proto_rawDescGZIP(), []int{0}
}

func (x *Item) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Item) GetCid() int64 {
	if x != nil {
		return x.Cid
	}
	return 0
}

func (x *Item) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type GetBackpackReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetBackpackReq) Reset() {
	*x = GetBackpackReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_backpack_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBackpackReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBackpackReq) ProtoMessage() {}

func (x *GetBackpackReq) ProtoReflect() protoreflect.Message {
	mi := &file_game_backpack_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBackpackReq.ProtoReflect.Descriptor instead.
func (*GetBackpackReq) Descriptor() ([]byte, []int) {
	return file_game_backpack_proto_rawDescGZIP(), []int{1}
}

type GetBackpackRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*Item `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *GetBackpackRsp) Reset() {
	*x = GetBackpackRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_backpack_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBackpackRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBackpackRsp) ProtoMessage() {}

func (x *GetBackpackRsp) ProtoReflect() protoreflect.Message {
	mi := &file_game_backpack_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBackpackRsp.ProtoReflect.Descriptor instead.
func (*GetBackpackRsp) Descriptor() ([]byte, []int) {
	return file_game_backpack_proto_rawDescGZIP(), []int{2}
}

func (x *GetBackpackRsp) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type AddItemReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cid   int64 `protobuf:"varint,1,opt,name=cid,proto3" json:"cid,omitempty"`
	Value int64 `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *AddItemReq) Reset() {
	*x = AddItemReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_backpack_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddItemReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddItemReq) ProtoMessage() {}

func (x *AddItemReq) ProtoReflect() protoreflect.Message {
	mi := &file_game_backpack_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddItemReq.ProtoReflect.Descriptor instead.
func (*AddItemReq) Descriptor() ([]byte, []int) {
	return file_game_backpack_proto_rawDescGZIP(), []int{3}
}

func (x *AddItemReq) GetCid() int64 {
	if x != nil {
		return x.Cid
	}
	return 0
}

func (x *AddItemReq) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type AddItemRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Item *Item `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
}

func (x *AddItemRsp) Reset() {
	*x = AddItemRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_backpack_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddItemRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddItemRsp) ProtoMessage() {}

func (x *AddItemRsp) ProtoReflect() protoreflect.Message {
	mi := &file_game_backpack_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddItemRsp.ProtoReflect.Descriptor instead.
func (*AddItemRsp) Descriptor() ([]byte, []int) {
	return file_game_backpack_proto_rawDescGZIP(), []int{4}
}

func (x *AddItemRsp) GetItem() *Item {
	if x != nil {
		return x.Item
	}
	return nil
}

type SubItemReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Value int64 `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *SubItemReq) Reset() {
	*x = SubItemReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_backpack_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubItemReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubItemReq) ProtoMessage() {}

func (x *SubItemReq) ProtoReflect() protoreflect.Message {
	mi := &file_game_backpack_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubItemReq.ProtoReflect.Descriptor instead.
func (*SubItemReq) Descriptor() ([]byte, []int) {
	return file_game_backpack_proto_rawDescGZIP(), []int{5}
}

func (x *SubItemReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SubItemReq) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type SubItemRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Item *Item `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
}

func (x *SubItemRsp) Reset() {
	*x = SubItemRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_backpack_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubItemRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubItemRsp) ProtoMessage() {}

func (x *SubItemRsp) ProtoReflect() protoreflect.Message {
	mi := &file_game_backpack_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubItemRsp.ProtoReflect.Descriptor instead.
func (*SubItemRsp) Descriptor() ([]byte, []int) {
	return file_game_backpack_proto_rawDescGZIP(), []int{6}
}

func (x *SubItemRsp) GetItem() *Item {
	if x != nil {
		return x.Item
	}
	return nil
}

var File_game_backpack_proto protoreflect.FileDescriptor

var file_game_backpack_proto_rawDesc = []byte{
	0x0a, 0x13, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x62, 0x61, 0x63, 0x6b, 0x70, 0x61, 0x63, 0x6b, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x67, 0x61, 0x6d, 0x65, 0x1a, 0x0b, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3e, 0x0a, 0x04, 0x49, 0x74, 0x65, 0x6d,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x10, 0x0a, 0x03, 0x63, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x63,
	0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x10, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x42,
	0x61, 0x63, 0x6b, 0x70, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x22, 0x32, 0x0a, 0x0e, 0x47, 0x65,
	0x74, 0x42, 0x61, 0x63, 0x6b, 0x70, 0x61, 0x63, 0x6b, 0x52, 0x73, 0x70, 0x12, 0x20, 0x0a, 0x05,
	0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x67, 0x61,
	0x6d, 0x65, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x34,
	0x0a, 0x0a, 0x41, 0x64, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03,
	0x63, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x63, 0x69, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x22, 0x2c, 0x0a, 0x0a, 0x41, 0x64, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x52,
	0x73, 0x70, 0x12, 0x1e, 0x0a, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0a, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x04, 0x69, 0x74,
	0x65, 0x6d, 0x22, 0x32, 0x0a, 0x0a, 0x53, 0x75, 0x62, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x71,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x2c, 0x0a, 0x0a, 0x53, 0x75, 0x62, 0x49, 0x74, 0x65,
	0x6d, 0x52, 0x73, 0x70, 0x12, 0x1e, 0x0a, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x04,
	0x69, 0x74, 0x65, 0x6d, 0x2a, 0x47, 0x0a, 0x11, 0x42, 0x61, 0x63, 0x6b, 0x70, 0x61, 0x63, 0x6b,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x32, 0x0a, 0x1a, 0x42, 0x61, 0x63,
	0x6b, 0x70, 0x61, 0x63, 0x6b, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x49, 0x74, 0x65, 0x6d, 0x4e, 0x6f,
	0x74, 0x45, 0x6e, 0x6f, 0x75, 0x67, 0x68, 0x10, 0x00, 0x1a, 0x12, 0x8a, 0xb5, 0x18, 0x0e, 0x12,
	0x0c, 0xe9, 0x81, 0x93, 0xe5, 0x85, 0xb7, 0xe4, 0xb8, 0x8d, 0xe8, 0xb6, 0xb3, 0x42, 0x0c, 0x5a,
	0x0a, 0x70, 0x62, 0x6d, 0x73, 0x67, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_game_backpack_proto_rawDescOnce sync.Once
	file_game_backpack_proto_rawDescData = file_game_backpack_proto_rawDesc
)

func file_game_backpack_proto_rawDescGZIP() []byte {
	file_game_backpack_proto_rawDescOnce.Do(func() {
		file_game_backpack_proto_rawDescData = protoimpl.X.CompressGZIP(file_game_backpack_proto_rawDescData)
	})
	return file_game_backpack_proto_rawDescData
}

var file_game_backpack_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_game_backpack_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_game_backpack_proto_goTypes = []interface{}{
	(BackpackErrorCode)(0), // 0: game.BackpackErrorCode
	(*Item)(nil),           // 1: game.Item
	(*GetBackpackReq)(nil), // 2: game.GetBackpackReq
	(*GetBackpackRsp)(nil), // 3: game.GetBackpackRsp
	(*AddItemReq)(nil),     // 4: game.AddItemReq
	(*AddItemRsp)(nil),     // 5: game.AddItemRsp
	(*SubItemReq)(nil),     // 6: game.SubItemReq
	(*SubItemRsp)(nil),     // 7: game.SubItemRsp
}
var file_game_backpack_proto_depIdxs = []int32{
	1, // 0: game.GetBackpackRsp.items:type_name -> game.Item
	1, // 1: game.AddItemRsp.item:type_name -> game.Item
	1, // 2: game.SubItemRsp.item:type_name -> game.Item
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_game_backpack_proto_init() }
func file_game_backpack_proto_init() {
	if File_game_backpack_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_game_backpack_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_backpack_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBackpackReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_backpack_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBackpackRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_backpack_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddItemReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_backpack_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddItemRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_backpack_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubItemReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_backpack_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubItemRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_game_backpack_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_game_backpack_proto_goTypes,
		DependencyIndexes: file_game_backpack_proto_depIdxs,
		EnumInfos:         file_game_backpack_proto_enumTypes,
		MessageInfos:      file_game_backpack_proto_msgTypes,
	}.Build()
	File_game_backpack_proto = out.File
	file_game_backpack_proto_rawDesc = nil
	file_game_backpack_proto_goTypes = nil
	file_game_backpack_proto_depIdxs = nil
}
