// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.27.0--rc1
// source: game/echo.proto

package game

import (
	_ "github.com/ravinggo/game/common/basepb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EchoErrorCode int32

const (
	EchoErrorCode_EchoErrorTest1 EchoErrorCode = 0
)

// Enum value maps for EchoErrorCode.
var (
	EchoErrorCode_name = map[int32]string{
		0: "EchoErrorTest1",
	}
	EchoErrorCode_value = map[string]int32{
		"EchoErrorTest1": 0,
	}
)

func (x EchoErrorCode) Enum() *EchoErrorCode {
	p := new(EchoErrorCode)
	*p = x
	return p
}

func (x EchoErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EchoErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_game_echo_proto_enumTypes[0].Descriptor()
}

func (EchoErrorCode) Type() protoreflect.EnumType {
	return &file_game_echo_proto_enumTypes[0]
}

func (x EchoErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EchoErrorCode.Descriptor instead.
func (EchoErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_game_echo_proto_rawDescGZIP(), []int{0}
}

type LoginSuccessReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserName string `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
}

func (x *LoginSuccessReq) Reset() {
	*x = LoginSuccessReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_echo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginSuccessReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginSuccessReq) ProtoMessage() {}

func (x *LoginSuccessReq) ProtoReflect() protoreflect.Message {
	mi := &file_game_echo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginSuccessReq.ProtoReflect.Descriptor instead.
func (*LoginSuccessReq) Descriptor() ([]byte, []int) {
	return file_game_echo_proto_rawDescGZIP(), []int{0}
}

func (x *LoginSuccessReq) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

type LoginSuccessRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserName string `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
}

func (x *LoginSuccessRsp) Reset() {
	*x = LoginSuccessRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_echo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginSuccessRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginSuccessRsp) ProtoMessage() {}

func (x *LoginSuccessRsp) ProtoReflect() protoreflect.Message {
	mi := &file_game_echo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginSuccessRsp.ProtoReflect.Descriptor instead.
func (*LoginSuccessRsp) Descriptor() ([]byte, []int) {
	return file_game_echo_proto_rawDescGZIP(), []int{1}
}

func (x *LoginSuccessRsp) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

type EchoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *EchoReq) Reset() {
	*x = EchoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_echo_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EchoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoReq) ProtoMessage() {}

func (x *EchoReq) ProtoReflect() protoreflect.Message {
	mi := &file_game_echo_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoReq.ProtoReflect.Descriptor instead.
func (*EchoReq) Descriptor() ([]byte, []int) {
	return file_game_echo_proto_rawDescGZIP(), []int{2}
}

func (x *EchoReq) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type EchoRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *EchoRsp) Reset() {
	*x = EchoRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_echo_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EchoRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoRsp) ProtoMessage() {}

func (x *EchoRsp) ProtoReflect() protoreflect.Message {
	mi := &file_game_echo_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoRsp.ProtoReflect.Descriptor instead.
func (*EchoRsp) Descriptor() ([]byte, []int) {
	return file_game_echo_proto_rawDescGZIP(), []int{3}
}

func (x *EchoRsp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_game_echo_proto protoreflect.FileDescriptor

var file_game_echo_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x65, 0x63, 0x68, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x04, 0x67, 0x61, 0x6d, 0x65, 0x1a, 0x0b, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2e, 0x0a, 0x0f, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x53, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x12, 0x1b, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72,
	0x4e, 0x61, 0x6d, 0x65, 0x22, 0x2e, 0x0a, 0x0f, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x53, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x52, 0x73, 0x70, 0x12, 0x1b, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72,
	0x4e, 0x61, 0x6d, 0x65, 0x22, 0x1b, 0x0a, 0x07, 0x45, 0x63, 0x68, 0x6f, 0x52, 0x65, 0x71, 0x12,
	0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73,
	0x67, 0x22, 0x1b, 0x0a, 0x07, 0x45, 0x63, 0x68, 0x6f, 0x52, 0x73, 0x70, 0x12, 0x10, 0x0a, 0x03,
	0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x2a, 0x38,
	0x0a, 0x0d, 0x45, 0x63, 0x68, 0x6f, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12,
	0x27, 0x0a, 0x0e, 0x45, 0x63, 0x68, 0x6f, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x54, 0x65, 0x73, 0x74,
	0x31, 0x10, 0x00, 0x1a, 0x13, 0x8a, 0xb5, 0x18, 0x0f, 0x12, 0x0d, 0xe6, 0xb5, 0x8b, 0xe8, 0xaf,
	0x95, 0xe9, 0x94, 0x99, 0xe8, 0xaf, 0xaf, 0x31, 0x42, 0x0c, 0x5a, 0x0a, 0x70, 0x62, 0x6d, 0x73,
	0x67, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_game_echo_proto_rawDescOnce sync.Once
	file_game_echo_proto_rawDescData = file_game_echo_proto_rawDesc
)

func file_game_echo_proto_rawDescGZIP() []byte {
	file_game_echo_proto_rawDescOnce.Do(func() {
		file_game_echo_proto_rawDescData = protoimpl.X.CompressGZIP(file_game_echo_proto_rawDescData)
	})
	return file_game_echo_proto_rawDescData
}

var file_game_echo_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_game_echo_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_game_echo_proto_goTypes = []interface{}{
	(EchoErrorCode)(0),      // 0: game.EchoErrorCode
	(*LoginSuccessReq)(nil), // 1: game.LoginSuccessReq
	(*LoginSuccessRsp)(nil), // 2: game.LoginSuccessRsp
	(*EchoReq)(nil),         // 3: game.EchoReq
	(*EchoRsp)(nil),         // 4: game.EchoRsp
}
var file_game_echo_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_game_echo_proto_init() }
func file_game_echo_proto_init() {
	if File_game_echo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_game_echo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginSuccessReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_echo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginSuccessRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_echo_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EchoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_echo_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EchoRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_game_echo_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_game_echo_proto_goTypes,
		DependencyIndexes: file_game_echo_proto_depIdxs,
		EnumInfos:         file_game_echo_proto_enumTypes,
		MessageInfos:      file_game_echo_proto_msgTypes,
	}.Build()
	File_game_echo_proto = out.File
	file_game_echo_proto_rawDesc = nil
	file_game_echo_proto_goTypes = nil
	file_game_echo_proto_depIdxs = nil
}
