// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: login/login.proto

package login

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	github_com_mailru_easyjson_buffer "github.com/mailru/easyjson/buffer"
	github_com_mailru_easyjson_jwriter "github.com/mailru/easyjson/jwriter"
	_ "github.com/ravinggo/game/common/basepb"
	github_com_ravinggo_tools_jsonany "github.com/ravinggo/tools/jsonany"
	google_golang_org_protobuf_reflect_protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	io "io"
	math "math"
	math_bits "math/bits"
	strconv "strconv"
	unsafe "unsafe"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type LoginErrorCode int32

const (
	LoginErrorCode_LoginErrorInvalidLoginType          LoginErrorCode = 0
	LoginErrorCode_LoginErrorTokenExpired              LoginErrorCode = 1
	LoginErrorCode_LoginErrorAccountIsNotRegistered    LoginErrorCode = 2
	LoginErrorCode_LoginErrorAccountIsRegistered       LoginErrorCode = 3
	LoginErrorCode_LoginErrorFormatError               LoginErrorCode = 4
	LoginErrorCode_LoginErrorPasswordFormatError       LoginErrorCode = 5
	LoginErrorCode_LoginErrorNotRealNameAuthentication LoginErrorCode = 6
	LoginErrorCode_LoginErrorAccountIsWrong            LoginErrorCode = 7
	LoginErrorCode_LoginErrorAuthenticationNotApproved LoginErrorCode = 8
	LoginErrorCode_LoginErrorAgeLimit                  LoginErrorCode = 9
	LoginErrorCode_LoginErrorLimitPlayTimeConfigWrong  LoginErrorCode = 10
	LoginErrorCode_LoginErrorFeedbackContentTooLong    LoginErrorCode = 11
	LoginErrorCode_LoginErrorFeedbackContactTooLong    LoginErrorCode = 12
	LoginErrorCode_LoginErrorTokenExpiredIsReconnect   LoginErrorCode = 13
)

var LoginErrorCode_name = map[int32]string{
	0:  "LoginErrorInvalidLoginType",
	1:  "LoginErrorTokenExpired",
	2:  "LoginErrorAccountIsNotRegistered",
	3:  "LoginErrorAccountIsRegistered",
	4:  "LoginErrorFormatError",
	5:  "LoginErrorPasswordFormatError",
	6:  "LoginErrorNotRealNameAuthentication",
	7:  "LoginErrorAccountIsWrong",
	8:  "LoginErrorAuthenticationNotApproved",
	9:  "LoginErrorAgeLimit",
	10: "LoginErrorLimitPlayTimeConfigWrong",
	11: "LoginErrorFeedbackContentTooLong",
	12: "LoginErrorFeedbackContactTooLong",
	13: "LoginErrorTokenExpiredIsReconnect",
}

var LoginErrorCode_value = map[string]int32{
	"LoginErrorInvalidLoginType":          0,
	"LoginErrorTokenExpired":              1,
	"LoginErrorAccountIsNotRegistered":    2,
	"LoginErrorAccountIsRegistered":       3,
	"LoginErrorFormatError":               4,
	"LoginErrorPasswordFormatError":       5,
	"LoginErrorNotRealNameAuthentication": 6,
	"LoginErrorAccountIsWrong":            7,
	"LoginErrorAuthenticationNotApproved": 8,
	"LoginErrorAgeLimit":                  9,
	"LoginErrorLimitPlayTimeConfigWrong":  10,
	"LoginErrorFeedbackContentTooLong":    11,
	"LoginErrorFeedbackContactTooLong":    12,
	"LoginErrorTokenExpiredIsReconnect":   13,
}

func (LoginErrorCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6fe61ab550dd3bc4, []int{0}
}

type LoginReq struct {
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (m *LoginReq) Reset()      { *m = LoginReq{} }
func (*LoginReq) ProtoMessage() {}
func (*LoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_6fe61ab550dd3bc4, []int{0}
}
func (m *LoginReq) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LoginReq.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReq.Merge(m, src)
}
func (m *LoginReq) XXX_Size() int {
	return m.Size()
}
func (m *LoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReq proto.InternalMessageInfo

func (m *LoginReq) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (*LoginReq) XXX_MessageName() string {
	return "login.LoginReq"
}

type LoginRsp struct {
	LoginResult int64 `protobuf:"varint,1,opt,name=login_result,json=loginResult,proto3" json:"login_result,omitempty"`
}

func (m *LoginRsp) Reset()      { *m = LoginRsp{} }
func (*LoginRsp) ProtoMessage() {}
func (*LoginRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_6fe61ab550dd3bc4, []int{1}
}
func (m *LoginRsp) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LoginRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LoginRsp.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LoginRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRsp.Merge(m, src)
}
func (m *LoginRsp) XXX_Size() int {
	return m.Size()
}
func (m *LoginRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRsp.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRsp proto.InternalMessageInfo

func (m *LoginRsp) GetLoginResult() int64 {
	if m != nil {
		return m.LoginResult
	}
	return 0
}

func (*LoginRsp) XXX_MessageName() string {
	return "login.LoginRsp"
}
func init() {
	proto.RegisterEnum("login.LoginErrorCode", LoginErrorCode_name, LoginErrorCode_value)
	proto.RegisterType((*LoginReq)(nil), "login.LoginReq")
	proto.RegisterType((*LoginRsp)(nil), "login.LoginRsp")
}

func init() { proto.RegisterFile("login/login.proto", fileDescriptor_6fe61ab550dd3bc4) }

var fileDescriptor_6fe61ab550dd3bc4 = []byte{
	// 772 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x94, 0xdf, 0x4f, 0x23, 0x55,
	0x14, 0xc7, 0x3b, 0xbb, 0xee, 0x2e, 0x3b, 0x45, 0x9c, 0xbd, 0x59, 0x74, 0x32, 0x9b, 0x9d, 0x6c,
	0xd9, 0xc4, 0x5d, 0x37, 0xae, 0x12, 0x37, 0x31, 0x31, 0xf8, 0x52, 0x10, 0x12, 0x12, 0x82, 0xa4,
	0x36, 0x31, 0xf1, 0xc5, 0x0c, 0xed, 0xb5, 0x4e, 0x68, 0xe7, 0x8e, 0x33, 0x53, 0x94, 0x37, 0x6a,
	0xa0, 0x34, 0xa3, 0xb5, 0x7d, 0x00, 0x1b, 0x48, 0x83, 0x3c, 0x68, 0x83, 0x04, 0xdb, 0x00, 0x1d,
	0xda, 0x5a, 0x90, 0x57, 0x1e, 0x79, 0xe4, 0x51, 0x5b, 0xee, 0xfc, 0x78, 0xf3, 0x4f, 0xd8, 0xcc,
	0x4c, 0x4b, 0xdb, 0xa4, 0xbc, 0x4c, 0xe6, 0x9e, 0x7b, 0xbe, 0x9f, 0xef, 0xb9, 0xe7, 0xfe, 0x20,
	0x1f, 0x44, 0x51, 0x84, 0x17, 0x3e, 0x74, 0xbe, 0x1f, 0x88, 0x12, 0x52, 0x10, 0xb8, 0xe3, 0x0c,
	0x18, 0x2f, 0x94, 0x24, 0x24, 0xb9, 0xb1, 0x91, 0x71, 0x72, 0x60, 0xc6, 0x8e, 0x06, 0xe0, 0x77,
	0x80, 0x21, 0x07, 0xe2, 0x32, 0x94, 0x04, 0x2e, 0x06, 0x69, 0xe2, 0x09, 0xf1, 0xfc, 0x7e, 0xe0,
	0x7a, 0x6c, 0xcf, 0x89, 0x9c, 0x2c, 0x7f, 0x8f, 0xa4, 0x30, 0x7d, 0xcb, 0x9d, 0x6b, 0x8f, 0x47,
	0x5e, 0xb6, 0x19, 0xb2, 0x08, 0x7c, 0xe4, 0xa0, 0xe3, 0xf2, 0xb5, 0x04, 0xe5, 0x78, 0x54, 0x71,
	0x38, 0xb7, 0x03, 0xde, 0xa8, 0xeb, 0x61, 0x87, 0x5e, 0xec, 0xdd, 0x23, 0x87, 0x9c, 0xfc, 0x49,
	0xbb, 0x8e, 0x09, 0x14, 0x86, 0x60, 0x8c, 0x64, 0x3a, 0x91, 0x69, 0x61, 0x91, 0x8b, 0xf2, 0x61,
	0x27, 0x10, 0x5c, 0x12, 0x21, 0xe5, 0x61, 0x1e, 0xa9, 0x1a, 0xfd, 0x0e, 0x18, 0xd6, 0x73, 0x3b,
	0xfa, 0x46, 0xca, 0xd8, 0x5a, 0x31, 0x36, 0xeb, 0xf8, 0x74, 0xc3, 0x38, 0xa8, 0xe3, 0xed, 0x9f,
	0xc0, 0x28, 0xf9, 0x76, 0x47, 0x1c, 0x44, 0x0b, 0x50, 0x98, 0xfc, 0x41, 0xe4, 0x25, 0x18, 0xa6,
	0x08, 0xe6, 0xa1, 0xaa, 0xd1, 0x14, 0x18, 0x52, 0xec, 0x28, 0xae, 0x1c, 0x9a, 0x67, 0x6b, 0x7a,
	0xfe, 0x37, 0x30, 0x46, 0x3e, 0xe9, 0x28, 0xfc, 0xa1, 0x10, 0x8a, 0x0b, 0xca, 0xb4, 0x3c, 0x8b,
	0x94, 0x00, 0x8c, 0xf0, 0xb2, 0x02, 0x6d, 0xed, 0x2d, 0x66, 0x58, 0xd5, 0xe8, 0x07, 0xe0, 0x2d,
	0xb3, 0x5c, 0xc0, 0x99, 0x8a, 0x9e, 0xdf, 0xd3, 0x8f, 0x76, 0x71, 0xf2, 0x67, 0xe0, 0x27, 0x1f,
	0xf7, 0x11, 0x77, 0x29, 0x6f, 0x33, 0xac, 0xaa, 0xd1, 0x0c, 0xa0, 0x5d, 0x25, 0xae, 0x1c, 0xba,
	0x4a, 0xb3, 0x54, 0x71, 0xeb, 0x06, 0x9f, 0x92, 0xc3, 0x1d, 0xc4, 0x14, 0x92, 0x62, 0x9c, 0xe2,
	0xfc, 0x52, 0x6f, 0x30, 0x3e, 0x55, 0xa3, 0x1f, 0x83, 0x47, 0x2d, 0xd3, 0x9d, 0x13, 0x7c, 0x92,
	0xb9, 0xaa, 0xa6, 0x8d, 0xfd, 0x02, 0xce, 0xa6, 0xcc, 0x42, 0x42, 0x3f, 0xf8, 0x11, 0x7c, 0xd6,
	0x5d, 0xc0, 0x5c, 0x6b, 0x13, 0xba, 0x29, 0x77, 0xda, 0x14, 0x5c, 0x4a, 0x1a, 0x3b, 0x89, 0x9b,
	0x28, 0x4f, 0x3b, 0x14, 0x67, 0xe9, 0x5c, 0x74, 0x96, 0x8b, 0x41, 0x7f, 0x5c, 0xf9, 0x16, 0x0a,
	0x0a, 0x1f, 0xe2, 0x14, 0x1e, 0x09, 0xd4, 0xdd, 0x76, 0xef, 0xaf, 0xdb, 0x80, 0x8b, 0xdb, 0x38,
	0x9b, 0x36, 0x8b, 0xbf, 0x9b, 0xa5, 0x04, 0xf8, 0x98, 0xa4, 0xfb, 0x34, 0xe3, 0x4b, 0x09, 0x09,
	0x11, 0xea, 0x1e, 0x43, 0xab, 0x1a, 0xfd, 0x10, 0x80, 0x56, 0x1f, 0x9c, 0x62, 0xac, 0xf5, 0x4d,
	0xb3, 0x54, 0xea, 0x75, 0xef, 0xb5, 0x9c, 0x45, 0x8a, 0x5f, 0x14, 0x25, 0xb4, 0x08, 0xc3, 0xd4,
	0x40, 0xaf, 0xbb, 0x6b, 0x7a, 0x55, 0x4d, 0x5b, 0xcb, 0x5b, 0xe6, 0xd9, 0x1a, 0x78, 0x41, 0x82,
	0x2e, 0x4a, 0x04, 0xce, 0xf0, 0x31, 0x5e, 0xa1, 0xee, 0x33, 0x40, 0xd5, 0xe8, 0x21, 0x30, 0x88,
	0x6b, 0x65, 0xeb, 0x9f, 0x15, 0x6b, 0x33, 0x8b, 0x53, 0xc7, 0xe0, 0x73, 0x72, 0xa4, 0x93, 0xeb,
	0x24, 0xce, 0x45, 0xb9, 0xa5, 0x20, 0x1f, 0x83, 0x13, 0x48, 0xf8, 0x86, 0x8f, 0xb8, 0x35, 0x93,
	0xcc, 0x33, 0x55, 0xa3, 0x9f, 0x02, 0x9f, 0xbd, 0xdf, 0xa9, 0x2c, 0xae, 0x95, 0xf5, 0x6a, 0xd5,
	0xf8, 0xe5, 0x4f, 0x3d, 0x77, 0x6c, 0xe5, 0xca, 0xd6, 0x6a, 0xda, 0x38, 0x2d, 0xb6, 0x96, 0xf0,
	0x45, 0xf7, 0x21, 0x9a, 0x82, 0x30, 0x3c, 0xcf, 0x85, 0x16, 0x26, 0x90, 0xa0, 0x40, 0x41, 0x09,
	0x22, 0x34, 0x63, 0xe3, 0xbc, 0xcc, 0x4b, 0x55, 0xa3, 0xdf, 0x03, 0xcf, 0x70, 0x26, 0x6d, 0x15,
	0x52, 0x38, 0xb9, 0x8a, 0x8b, 0x35, 0x6b, 0xe3, 0x0c, 0xff, 0x5d, 0xb0, 0xf2, 0xcb, 0x38, 0xbf,
	0xfb, 0xd1, 0xe8, 0x28, 0xfe, 0x2b, 0x67, 0xec, 0x17, 0xae, 0xea, 0x7f, 0xe0, 0xe4, 0x2a, 0x08,
	0xdc, 0x04, 0xe5, 0x42, 0xd7, 0xd0, 0x41, 0xe6, 0x7d, 0x55, 0xa3, 0x9f, 0x83, 0x77, 0xcd, 0xc4,
	0xba, 0x71, 0x54, 0xd7, 0x7f, 0xad, 0xe1, 0x93, 0x4c, 0x37, 0xf4, 0x55, 0x2f, 0x73, 0x8c, 0xf4,
	0xf5, 0xbf, 0x1f, 0xf6, 0xa9, 0x0d, 0x21, 0x41, 0x80, 0x21, 0x85, 0x7a, 0xb3, 0xff, 0x55, 0x19,
	0xff, 0xe4, 0xf2, 0x3f, 0xd6, 0xb3, 0xdb, 0x60, 0x89, 0xf3, 0x06, 0x4b, 0x5c, 0x34, 0x58, 0xe2,
	0xdf, 0x06, 0x4b, 0x98, 0x0d, 0xd6, 0xf3, 0x7f, 0x83, 0x25, 0xb2, 0x4d, 0xd6, 0x73, 0xde, 0x64,
	0x89, 0x8b, 0x26, 0xeb, 0xb9, 0x6c, 0xb2, 0x9e, 0xaf, 0xbc, 0xe2, 0x7c, 0x4c, 0x8e, 0xb8, 0x8f,
	0xce, 0xfc, 0x5d, 0xe7, 0x85, 0x79, 0xf5, 0x3a, 0x00, 0x00, 0xff, 0xff, 0x0d, 0xe8, 0x99, 0x8a,
	0x8a, 0x04, 0x00, 0x00,
}

func (x LoginErrorCode) String() string {
	s, ok := LoginErrorCode_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}
func (this *LoginReq) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*LoginReq)
	if !ok {
		that2, ok := that.(LoginReq)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Username != that1.Username {
		return false
	}
	if this.Password != that1.Password {
		return false
	}
	return true
}
func (this *LoginRsp) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*LoginRsp)
	if !ok {
		that2, ok := that.(LoginRsp)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.LoginResult != that1.LoginResult {
		return false
	}
	return true
}
func (m *LoginReq) ProtoReflect() google_golang_org_protobuf_reflect_protoreflect.Message {
	return nil
}
func (m *LoginRsp) ProtoReflect() google_golang_org_protobuf_reflect_protoreflect.Message {
	return nil
}
func (m *LoginReq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LoginReq) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *LoginReq) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Password) > 0 {
		i -= len(m.Password)
		copy(dAtA[i:], m.Password)
		i = encodeVarintLogin(dAtA, i, uint64(len(m.Password)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Username) > 0 {
		i -= len(m.Username)
		copy(dAtA[i:], m.Username)
		i = encodeVarintLogin(dAtA, i, uint64(len(m.Username)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *LoginRsp) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LoginRsp) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *LoginRsp) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.LoginResult != 0 {
		i = encodeVarintLogin(dAtA, i, uint64(m.LoginResult))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintLogin(dAtA []byte, offset int, v uint64) int {
	offset -= sovLogin(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}

var _ = github_com_ravinggo_tools_jsonany.Any{}

func (m *LoginReq) JsonBytes(w *github_com_mailru_easyjson_jwriter.Writer) {
	if m == nil {
		w.RawString("null")
		return
	}

	w.RawByte('{')
	needWriteComma := false
	if m.Username != "" {
		w.RawByte('"')
		w.RawString("username")
		w.RawByte('"')
		w.RawByte(':')
		w.String(m.Username)
		needWriteComma = true
	}
	if m.Password != "" {
		if needWriteComma {
			w.RawByte(',')
		}
		w.RawByte('"')
		w.RawString("password")
		w.RawByte('"')
		w.RawByte(':')
		w.String(m.Password)
		needWriteComma = true
	}
	_ = needWriteComma
	w.RawByte('}')

}

func (m *LoginRsp) JsonBytes(w *github_com_mailru_easyjson_jwriter.Writer) {
	if m == nil {
		w.RawString("null")
		return
	}

	w.RawByte('{')
	needWriteComma := false
	if m.LoginResult != 0 {
		w.RawByte('"')
		w.RawString("login_result")
		w.RawByte('"')
		w.RawByte(':')
		w.Int64(int64(m.LoginResult))
		needWriteComma = true
	}
	_ = needWriteComma
	w.RawByte('}')

}

func (m *LoginReq) MarshalJSON() ([]byte, error) {
	w := github_com_mailru_easyjson_jwriter.Writer{Buffer: github_com_mailru_easyjson_buffer.Buffer{Buf: make([]byte, 0, 2048)}}
	m.JsonBytes(&w)
	return w.BuildBytes()
}
func (m *LoginReq) String() string {
	d, _ := m.MarshalJSON()
	return *(*string)(unsafe.Pointer(&d))
}
func (m *LoginReq) GoString() string {
	return m.String()
}

func (m *LoginRsp) MarshalJSON() ([]byte, error) {
	w := github_com_mailru_easyjson_jwriter.Writer{Buffer: github_com_mailru_easyjson_buffer.Buffer{Buf: make([]byte, 0, 2048)}}
	m.JsonBytes(&w)
	return w.BuildBytes()
}
func (m *LoginRsp) String() string {
	d, _ := m.MarshalJSON()
	return *(*string)(unsafe.Pointer(&d))
}
func (m *LoginRsp) GoString() string {
	return m.String()
}

func (m *LoginReq) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Username)
	if l > 0 {
		n += 1 + l + sovLogin(uint64(l))
	}
	l = len(m.Password)
	if l > 0 {
		n += 1 + l + sovLogin(uint64(l))
	}
	return n
}

func (m *LoginRsp) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.LoginResult != 0 {
		n += 1 + sovLogin(uint64(m.LoginResult))
	}
	return n
}

func sovLogin(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozLogin(x uint64) (n int) {
	return sovLogin(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *LoginReq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLogin
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: LoginReq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: LoginReq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Username", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLogin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLogin
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLogin
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Username = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Password", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLogin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLogin
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLogin
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Password = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipLogin(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLogin
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *LoginRsp) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLogin
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: LoginRsp: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: LoginRsp: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LoginResult", wireType)
			}
			m.LoginResult = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLogin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LoginResult |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipLogin(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLogin
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipLogin(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowLogin
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowLogin
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowLogin
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthLogin
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupLogin
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthLogin
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthLogin        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowLogin          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupLogin = fmt.Errorf("proto: unexpected end of group")
)
